main: com.potionenchants.plugin.Main
name: PotionDippedItems
version: 1.1
author: Dguto9 
description: Allows players to add potion effects to their weapons and armor. For example, poison-dipped sword applies poison to the one being hit, while strength-dipped armor applies strength to the one wearing it whenever they are hit.
api-version: 1.16
